[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[build.nixpacks]
nodeVersion = "22"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
